spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommercedb
    username: postgres
    password: 230204
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 50
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      separator: ;;
      data-locations: classpath:data.sql
#      data-locations: classpath:data.sql, classpath:data_crawl.sql
#  204863
#  "230204"